version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: 'terraform'
    directory: '/terraform' # Location of package manifests
    schedule:
      interval: 'daily'