# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: e0322737dccad136b751416f9e45d9980fe18435  # frozen: v1.96.2
    hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint