name: Terraform Plan

on:
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_plan:
    uses: RoyalAholdDelhaize/gso-tech-workflows/.github/workflows/plan.yml@0.31.0
    secrets: inherit
    with:
      runner: adusa
      terraform_version: 1.14.3
